import Figures from "../components/Figures.jsx";
import { Histogram, HBars, Legend } from "../components/Charts.jsx";
import { Async, Badge, Empty, Panel, PageHead, Stats } from "../components/ui.jsx";
import { dash, num, pct } from "../lib/format.js";
import { useApi } from "../lib/hooks.js";

export default function DataPage() {
  const state = useApi("/api/data/summary");
  return (
    <>
      <PageHead title="Data">The AI4I 2020 sensor dataset that trains the model: how much of it there is, how rare failures are, and how each sensor is distributed.</PageHead>
      <Async state={state}>
        {(d) => {
          if (!d.available) return <Panel><Empty title="Dataset not found">Expected at {d.path}. Run the pipeline to download or generate it.</Empty></Panel>;
          const total = d.class_counts.normal + d.class_counts.failure;
          return (
            <>
              <Panel flush>
                <Stats items={[
                  { label: "Observations", value: num(d.rows, 0), note: `${d.columns} columns` },
                  { label: "Failures", value: num(d.class_counts.failure, 0), note: `${num(d.failure_rate_pct)}% of rows`, tone: "warn" },
                  { label: "Normal runs", value: num(d.class_counts.normal, 0) },
                  { label: "Validation", value: d.quality ? (d.quality.is_valid ? "Passed" : "Failed") : dash, tone: d.quality ? (d.quality.is_valid ? "ok" : "bad") : undefined, note: d.quality ? `${d.quality.duplicate_rows} duplicates, ${Object.keys(d.quality.missing_values || {}).length} columns with gaps` : "No report" },
                ]} />
              </Panel>

              <div className="grid cols-3">
                <Panel title="Class balance" sub="Why recall matters more than accuracy">
                  <div className="stack">
                    <div className="stackbar" role="img" aria-label={`${pct(d.class_counts.failure / total, 2)} failures`}>
                      <i style={{ width: `${(d.class_counts.normal / total) * 100}%`, background: "var(--accent)", opacity: 0.55 }} />
                      <i style={{ width: `${Math.max(0.8, (d.class_counts.failure / total) * 100)}%`, background: "var(--bad)" }} />
                    </div>
                    <Legend items={[{ name: `Normal ${num(d.class_counts.normal, 0)}`, color: "var(--accent)" }, { name: `Failure ${num(d.class_counts.failure, 0)}`, color: "var(--bad)" }]} />
                    <p className="muted small">A model that always answers "normal" would be {pct(d.class_counts.normal / total)} accurate and catch no failures.</p>
                  </div>
                </Panel>
                <Panel title="Failure modes" sub="A row can have more than one">
                  <HBars labelWidth={150} items={d.failure_modes.map((f) => ({ label: f.name, value: f.count, title: f.mode }))} format={(v) => num(v, 0)} />
                </Panel>
                <Panel title="By product quality type">
                  <HBars labelWidth={70} max={Math.max(...d.by_type.map((t) => t.failure_rate_pct), 1) * 1.2}
                    items={d.by_type.map((t) => ({ label: { L: "Low", M: "Medium", H: "High" }[t.type], value: t.failure_rate_pct, title: `${t.failures} of ${t.count} rows` }))} format={(v) => `${v.toFixed(1)}%`} />
                  <p className="muted small" style={{ marginTop: 12 }}>Failure rate per type. Low-quality product runs fail most often.</p>
                </Panel>
              </div>

              <Panel title="Sensor distributions" sub="Red marks rows that ended in a failure" flush>
                <div className="grid cols-3" style={{ gap: 0 }}>
                  {d.sensors.map((s) => (
                    <div className="mini-hist" key={s.column}>
                      <div className="row between"><strong>{s.label}</strong><span className="faint small">{s.unit}</span></div>
                      <Histogram hist={s.hist} unit={s.unit} />
                      <div className="small muted">Mean {num(s.mean, 1)} · Std {num(s.std, 1)} · Range {num(s.min, 1)} to {num(s.max, 1)}</div>
                    </div>
                  ))}
                </div>
              </Panel>

              <Panel title="Exploratory analysis" sub="Generated by the EDA notebook and training runs"><Figures figures={d.figures.filter((f) => !f.name.startsWith("cm_") && !f.name.startsWith("model_comparison"))} /></Panel>
            </>
          );
        }}
      </Async>
    </>
  );
}
